spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:10089/dor_manage?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useAffectedRows=true&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 1000
    initialSize: 100
    maxWait: 60000
    minIdle: 500
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  redis:
    host: 127.0.0.1
    port: 6379
    password:

server:
  address: 0.0.0.0
  port: 8888

#OSS参数配置
oss:
  ossEndpoint:
  accessKeyId:
  accessKeySecret:
  bucketName:

#日志
logging:
  level:
    com.xl.study.studytest.shiro.beans.mapper: debug

